//+------------------------------------------------------------------+
//| PortfolioEA.mq5 - per-engine performance tracker                   |
//|                                  Copyright 2026, Master Strategy   |
//|                                                                     |
//| Tracks the 65 engines that AllEnginesEA runs (or the 65 standalone  |
//| EAs) by their magic number.  It NEVER trades: no CTrade, no order   |
//| sends, no position modification - only history and market reads.    |
//|                                                                     |
//| This is the dashboard EA.  AllEnginesEA deliberately contains no    |
//| dashboard logic; the two are coupled only by the magic numbers and  |
//| the static identity file MQL5\Files\PortfolioEA\engines.csv,        |
//| generated by portfolio-EA/gen_portfolio_ea.py.                      |
//|                                                                     |
//| Reads  : account history + open positions                           |
//| Writes : MQL5\Files\PortfolioEA\performance.csv                     |
//| Shows  : optional on-chart panel (one line per engine, by net)      |
//|                                                                     |
//| Verdict per engine (a suggestion for the AllEnginesEA switches):    |
//|   DROP     - at least InpMinTrades closed and net negative          |
//|   REVIEW   - expectancy <= 0 or closed DD above InpReviewDdPct      |
//|   TOO_FEW  - not enough closed trades to judge yet                  |
//|   KEEP     - otherwise                                              |
//+------------------------------------------------------------------+
#property copyright "Master Strategy"
#property version   "1.00"
#property description "Read-only tracker: per-engine performance by magic number."
#property description "Needs MQL5\\Files\\PortfolioEA\\engines.csv for engine names (optional)."

//--- inputs ----------------------------------------------------------------
input int    InpRefreshSec   = 5;      // refresh interval (seconds)
input int    InpDaysBack     = 30;     // history window in days (0 = all available)
input bool   InpWriteCsv     = true;   // write performance.csv
input bool   InpShowPanel    = true;   // draw the on-chart panel
input int    InpPanelRows    = 20;     // panel rows to display
input int    InpPanelX       = 15;     // panel X offset (pixels)
input int    InpPanelY       = 25;     // panel Y offset (pixels)
input int    InpFontSize     = 9;      // panel font size
input bool   InpShowBgBox    = true;   // draw semi-transparent background box
input int    InpMinTrades    = 20;     // closed trades before DROP is allowed
input double InpReviewDdPct  = 25.0;   // closed-DD % of base that triggers REVIEW
input double InpBaseBalance  = 0.0;    // DD base (0 = balance when this EA starts)
input bool   InpRegistryOnly = true;   // ignore magics that are not in engines.csv
input string InpIdentityFile = "PortfolioEA\\engines.csv";     // under MQL5\Files
input string InpReportFile   = "PortfolioEA\\performance.csv"; // under MQL5\Files

//--- engine row ------------------------------------------------------------
struct SEngineRow
{
   long     magic;
   string   name;
   string   tag;
   string   strategy;
   string   tf;
   bool     known;         // listed in engines.csv
   double   net;           // closed P/L (profit + swap + commission)
   int      closed;        // closed trades (entry-out deals)
   int      wins;
   int      losses;
   double   maxProfit;     // largest single-trade closed gain
   double   maxDd;         // max closed drawdown, account currency
   double   run;           // running sum (working value for the DD curve)
   double   peak;
   int      openPos;
   double   floating;
   string   verdict;
};

SEngineRow g_rows[];
int        g_count           = 0;
bool       g_identityLoaded  = false;
double     g_base            = 0.0;
double     g_totalNet        = 0.0;
double     g_totalFloat      = 0.0;
int        g_totalOpen       = 0;
string     g_panelPrefix     = "PFX_";

//--- entry-side money per (engine, position): a close must be judged on its own
//--- round turn even when two positions of the same engine are open at once
struct SPending
{
   long   magic;
   long   posId;
   double money;
};

//--- forward declarations (MQL5 compiles in order) -------------------------
void PendingAdd(SPending &store[], const long magic, const long posId, const double money);
double PendingTake(SPending &store[], const long magic, const long posId);
int  FindRow(const long magic);
int  EnsureRow(const long magic);
void LoadIdentity();
void Refresh();
void WriteCsv();
void DrawPanel();
void RemovePanel();

//+------------------------------------------------------------------+
//| row lookup / creation                                             |
//+------------------------------------------------------------------+
void PendingAdd(SPending &store[], const long magic, const long posId, const double money)
{
   if(posId == 0) return;
   for(int i = 0; i < ArraySize(store); i++)
      if(store[i].magic == magic && store[i].posId == posId)
      {
         store[i].money += money;
         return;
      }
   int n = ArraySize(store);
   if(ArrayResize(store, n + 1) != n + 1) return;
   store[n].magic = magic;
   store[n].posId = posId;
   store[n].money = money;
}

double PendingTake(SPending &store[], const long magic, const long posId)
{
   if(posId == 0) return 0.0;
   for(int i = 0; i < ArraySize(store); i++)
      if(store[i].magic == magic && store[i].posId == posId)
      {
         double money = store[i].money;
         ArrayRemove(store, i, 1);
         return money;
      }
   return 0.0;
}

int FindRow(const long magic)
{
   for(int i = 0; i < g_count; i++)
      if(g_rows[i].magic == magic) return i;
   return -1;
}

int EnsureRow(const long magic)
{
   int i = FindRow(magic);
   if(i >= 0) return i;
   if(ArrayResize(g_rows, g_count + 1) != g_count + 1)
   {
      PrintFormat("PortfolioEA tracker: out of memory for magic %d", (int)magic);
      return -1;
   }
   g_rows[g_count].magic    = magic;
   g_rows[g_count].tag      = "P" + IntegerToString(magic) + "|";
   g_rows[g_count].name     = "magic " + IntegerToString(magic);
   g_rows[g_count].strategy = "";
   g_rows[g_count].tf       = "";
   g_rows[g_count].known    = false;
   g_rows[g_count].net      = 0.0;
   g_rows[g_count].closed   = 0;
   g_rows[g_count].wins     = 0;
   g_rows[g_count].losses   = 0;
   g_rows[g_count].maxProfit = 0.0;
   g_rows[g_count].maxDd    = 0.0;
   g_rows[g_count].run      = 0.0;
   g_rows[g_count].peak     = 0.0;
   g_rows[g_count].openPos  = 0;
   g_rows[g_count].floating = 0.0;
   g_rows[g_count].verdict  = "NEW";
   g_count++;
   return g_count - 1;
}

//+------------------------------------------------------------------+
//| identity file: magic -> tag, engine, strategy, timeframe          |
//| read as text lines (fully deterministic CSV parsing)              |
//+------------------------------------------------------------------+
void LoadIdentity()
{
   int h = FileOpen(InpIdentityFile, FILE_READ | FILE_TXT | FILE_ANSI);
   if(h == INVALID_HANDLE)
   {
      PrintFormat("PortfolioEA tracker: %s not found (error %d) - engines will be shown by magic " +
                  "only.  Copy portfolio-EA/build/engines.csv into MQL5\\Files\\PortfolioEA\\.",
                  InpIdentityFile, GetLastError());
      return;
   }

   bool first = true;
   int  cMagic = 0, cTag = 1, cEa = 2, cStrategy = 3, cTf = 5;
   while(!FileIsEnding(h))
   {
      string line = FileReadString(h);
      if(StringLen(line) == 0) continue;
      string f[];
      int n = StringSplit(line, ',', f);
      if(n < 4) continue;

      if(first)
      {
         first = false;
         for(int i = 0; i < n; i++)
         {
            string key = f[i];
            StringTrimLeft(key); StringTrimRight(key);
            if(key == "magic")      cMagic = i;
            if(key == "tag")        cTag = i;
            if(key == "ea")         cEa = i;
            if(key == "strategy")   cStrategy = i;
            if(key == "timeframe")  cTf = i;
         }
         if(StringLen(f[cMagic]) == 0 || f[cMagic] == "magic") continue;   // header row
      }

      long magic = (long)StringToInteger(f[cMagic]);
      if(magic <= 0) continue;
      int idx = EnsureRow(magic);
      if(idx < 0) { FileClose(h); return; }
      if(cTag < n)        g_rows[idx].tag      = f[cTag];
      if(cEa < n)         g_rows[idx].name     = f[cEa];
      if(cStrategy < n)   g_rows[idx].strategy = f[cStrategy];
      if(cTf < n)         g_rows[idx].tf       = f[cTf];
      g_rows[idx].known = true;
   }
   FileClose(h);
   g_identityLoaded = (g_count > 0);
   PrintFormat("PortfolioEA tracker: identity loaded for %d engine(s)", g_count);
}

//+------------------------------------------------------------------+
//| refresh: history + positions -> rows                              |
//+------------------------------------------------------------------+
void Refresh()
{
   datetime from = (InpDaysBack > 0)
                   ? TimeCurrent() - (datetime)((long)InpDaysBack * 86400)
                   : (datetime)0;
   bool haveHistory = HistorySelect(from, TimeCurrent() + 60);
   if(!haveHistory)
      PrintFormat("PortfolioEA tracker: HistorySelect failed (error %d) - open positions only",
                  GetLastError());

   for(int i = 0; i < g_count; i++)
   {
      g_rows[i].net = 0.0; g_rows[i].closed = 0; g_rows[i].wins = 0;
      g_rows[i].losses = 0; g_rows[i].maxProfit = 0.0; g_rows[i].maxDd = 0.0; g_rows[i].run = 0.0;
      g_rows[i].peak = 0.0;
      g_rows[i].openPos = 0; g_rows[i].floating = 0.0;
      g_rows[i].verdict = "KEEP";
   }
   g_totalNet = 0.0; g_totalFloat = 0.0; g_totalOpen = 0;

   //--- pass 1: deals, in time order -> net, trades, win/loss, DD curve.
   //--- Commission is charged on the entry deal by many brokers, so entry-side
   //--- money is carried per position and folded into that position's closing
   //--- deal: net stays exact, the win/loss split uses the whole round turn, and
   //--- the drawdown curve sees each cost exactly once.
   SPending pend[];
   int deals = haveHistory ? HistoryDealsTotal() : 0;
   for(int d = 0; d < deals; d++)
   {
      ulong t = HistoryDealGetTicket(d);
      if(t == 0) continue;
      long magic = (long)HistoryDealGetInteger(t, DEAL_MAGIC);
      if(magic <= 0) continue;

      int i = FindRow(magic);
      if(i < 0)
      {
         if(g_identityLoaded && InpRegistryOnly) continue;    // not one of the engines
         i = EnsureRow(magic);
         if(i < 0) continue;
      }

      long   dtype = HistoryDealGetInteger(t, DEAL_TYPE);
      long   entry = HistoryDealGetInteger(t, DEAL_ENTRY);
      long   posId = HistoryDealGetInteger(t, DEAL_POSITION_ID);
      double money = HistoryDealGetDouble(t, DEAL_PROFIT)
                   + HistoryDealGetDouble(t, DEAL_SWAP)
                   + HistoryDealGetDouble(t, DEAL_COMMISSION);
      bool   isTrade = (dtype == DEAL_TYPE_BUY || dtype == DEAL_TYPE_SELL);

      if(isTrade && entry == DEAL_ENTRY_IN)
      {
         PendingAdd(pend, magic, posId, money);   // entry commission/swap
         continue;                                // not a closed trade
      }

      if(isTrade && (entry == DEAL_ENTRY_OUT || entry == DEAL_ENTRY_OUT_BY ||
                     entry == DEAL_ENTRY_INOUT))
      {
         double pl = money + PendingTake(pend, magic, posId);   // whole round turn
         g_rows[i].net += pl;
         g_rows[i].closed++;
         if(pl > 0.0)
         {
            g_rows[i].wins++;
            if(pl > g_rows[i].maxProfit) g_rows[i].maxProfit = pl;
         }
         else if(pl < 0.0) g_rows[i].losses++;

         g_rows[i].run += pl;
         if(g_rows[i].run > g_rows[i].peak) g_rows[i].peak = g_rows[i].run;
         double dd = g_rows[i].peak - g_rows[i].run;
         if(dd > g_rows[i].maxDd) g_rows[i].maxDd = dd;
         continue;
      }

      //--- everything else: a commission / charge / interest / dividend deal
      //--- (money on its own event) or a trade deal with an unexpected entry
      //--- flag - it lands in net and as one point on the DD curve
      g_rows[i].net += money;
      g_rows[i].run += money;
      if(g_rows[i].run > g_rows[i].peak) g_rows[i].peak = g_rows[i].run;
      double dd = g_rows[i].peak - g_rows[i].run;
      if(dd > g_rows[i].maxDd) g_rows[i].maxDd = dd;
   }

   //--- pass 2: open positions
   for(int p = PositionsTotal() - 1; p >= 0; p--)
   {
      ulong t = PositionGetTicket(p);
      if(t == 0) continue;
      if(!PositionSelectByTicket(t)) continue;
      long magic = (long)PositionGetInteger(POSITION_MAGIC);
      if(magic <= 0) continue;

      int i = FindRow(magic);
      if(i < 0)
      {
         if(g_identityLoaded && InpRegistryOnly) continue;
         i = EnsureRow(magic);
         if(i < 0) continue;
      }
      g_rows[i].openPos++;
      g_rows[i].floating += PositionGetDouble(POSITION_PROFIT)
                          + PositionGetDouble(POSITION_SWAP);
   }

   //--- verdicts + totals
   for(int i = 0; i < g_count; i++)
   {
      g_totalNet   += g_rows[i].net;
      g_totalFloat += g_rows[i].floating;
      g_totalOpen  += g_rows[i].openPos;

      double ddPct      = (g_base > 0.0) ? 100.0 * g_rows[i].maxDd / g_base : 0.0;
      double expectancy = (g_rows[i].closed > 0) ? g_rows[i].net / g_rows[i].closed : 0.0;
      bool   ddFlag     = (g_base > 0.0 && ddPct >= InpReviewDdPct);
      if(g_rows[i].closed == 0)
         g_rows[i].verdict = "TOO_FEW";
      else if(g_rows[i].closed < InpMinTrades)
         g_rows[i].verdict = ddFlag ? "REVIEW" : "TOO_FEW";
      else if(g_rows[i].net < 0.0)
         g_rows[i].verdict = "DROP";
      else if(expectancy <= 0.0 || ddFlag)
         g_rows[i].verdict = "REVIEW";
      else
         g_rows[i].verdict = "KEEP";
   }

   //--- sort: open positions first, then highest net, then most trades
   for(int a = 0; a < g_count - 1; a++)
      for(int b = 0; b < g_count - 1 - a; b++)
      {
         bool doSwap = false;
         // 1. prioritize engines with active open positions
         if(g_rows[b].openPos < g_rows[b + 1].openPos)
            doSwap = true;
         else if(g_rows[b].openPos == g_rows[b + 1].openPos)
         {
            // 2. prioritize highest net profit
            if(g_rows[b].net < g_rows[b + 1].net)
               doSwap = true;
            else if(g_rows[b].net == g_rows[b + 1].net)
            {
               // 3. prioritize engines with closed trades
               if(g_rows[b].closed < g_rows[b + 1].closed)
                  doSwap = true;
            }
         }

         if(doSwap)
         {
            SEngineRow tmp  = g_rows[b];
            g_rows[b]       = g_rows[b + 1];
            g_rows[b + 1]   = tmp;
         }
      }

   if(InpWriteCsv) WriteCsv();
   if(InpShowPanel) DrawPanel();
}

//+------------------------------------------------------------------+
//| CSV report                                                        |
//+------------------------------------------------------------------+
//--- FILE_CSV writes fields verbatim: a comma inside a value would shift every
//--- column after it, so text that comes from the identity file is sanitised
string CsvText(string s)
{
   StringReplace(s, ",", ";");
   StringReplace(s, "\r", " ");
   StringReplace(s, "\n", " ");
   return s;
}

void WriteCsv()
{
   FolderCreate("PortfolioEA");       // MQL5 does not create subfolders on write
   int h = FileOpen(InpReportFile, FILE_WRITE | FILE_CSV | FILE_ANSI, ',');
   if(h == INVALID_HANDLE)
   {
      PrintFormat("PortfolioEA tracker: cannot write %s (error %d) - create " +
                  "MQL5\\Files\\PortfolioEA if this persists", InpReportFile, GetLastError());
      return;
   }
   FileWrite(h, "magic", "tag", "engine", "strategy", "timeframe", "net", "max_profit", "trades",
             "wins", "losses", "win_pct", "max_dd", "dd_pct_of_base", "open_positions",
             "floating", "verdict", "switch");
   for(int i = 0; i < g_count; i++)
   {
      double winPct = (g_rows[i].wins + g_rows[i].losses > 0)
                      ? 100.0 * g_rows[i].wins / (g_rows[i].wins + g_rows[i].losses) : 0.0;
      double ddPct  = (g_base > 0.0) ? 100.0 * g_rows[i].maxDd / g_base : 0.0;
      FileWrite(h, IntegerToString(g_rows[i].magic), CsvText(g_rows[i].tag),
                CsvText(g_rows[i].name), CsvText(g_rows[i].strategy), CsvText(g_rows[i].tf),
                DoubleToString(g_rows[i].net, 2), DoubleToString(g_rows[i].maxProfit, 2),
                IntegerToString(g_rows[i].closed),
                IntegerToString(g_rows[i].wins), IntegerToString(g_rows[i].losses),
                DoubleToString(winPct, 1), DoubleToString(g_rows[i].maxDd, 2),
                DoubleToString(ddPct, 1), IntegerToString(g_rows[i].openPos),
                DoubleToString(g_rows[i].floating, 2), g_rows[i].verdict,
                "InpRun_" + IntegerToString(g_rows[i].magic));
   }
   //--- column alignment: 17 columns total
   //--- magic, tag, engine, strategy, tf, net, max_profit, trades, wins, losses, win_pct, max_dd, dd_pct, open_pos, floating, verdict, switch
   FileWrite(h, "TOTAL", "", "", "", "", DoubleToString(g_totalNet, 2), "", "", "", "",
             "", "", "", IntegerToString(g_totalOpen), DoubleToString(g_totalFloat, 2), "", "");
   FileClose(h);
}

//+------------------------------------------------------------------+
//| on-chart panel                                                    |
//+------------------------------------------------------------------+
void MakeLabel(const string name, const int x, const int y, const string text,
               const color clr, const int size, const bool bold = false)
{
   if(ObjectFind(0, name) < 0)
      ObjectCreate(0, name, OBJ_LABEL, 0, 0, 0);
   ObjectSetInteger(0, name, OBJPROP_CORNER, CORNER_LEFT_UPPER);
   ObjectSetInteger(0, name, OBJPROP_XDISTANCE, x);
   ObjectSetInteger(0, name, OBJPROP_YDISTANCE, y);
   ObjectSetInteger(0, name, OBJPROP_COLOR, clr);
   ObjectSetInteger(0, name, OBJPROP_FONTSIZE, size);
   ObjectSetInteger(0, name, OBJPROP_SELECTABLE, false);
   ObjectSetString(0, name, OBJPROP_FONT, "Consolas");
   ObjectSetString(0, name, OBJPROP_TEXT, text);
}

void DrawPanel()
{
   const int x = InpPanelX, y = InpPanelY;
   const int dy = InpFontSize + 6;
   const int size = InpFontSize;
   int shown = (InpPanelRows > 0) ? (int)MathMin(InpPanelRows, g_count) : g_count;

   //--- optional background box to guarantee readability over candlestick bars
   if(InpShowBgBox)
   {
      string bgName = g_panelPrefix + "bg";
      if(ObjectFind(0, bgName) < 0)
         ObjectCreate(0, bgName, OBJ_RECTANGLE_LABEL, 0, 0, 0);
      ObjectSetInteger(0, bgName, OBJPROP_CORNER, CORNER_LEFT_UPPER);
      ObjectSetInteger(0, bgName, OBJPROP_XDISTANCE, x - 6);
      ObjectSetInteger(0, bgName, OBJPROP_YDISTANCE, y - 6);
      ObjectSetInteger(0, bgName, OBJPROP_XSIZE, 710);
      ObjectSetInteger(0, bgName, OBJPROP_YSIZE, (shown + 4) * dy + 10);
      ObjectSetInteger(0, bgName, OBJPROP_BGCOLOR, C'16,18,22');
      ObjectSetInteger(0, bgName, OBJPROP_BORDER_COLOR, C'45,55,72');
      ObjectSetInteger(0, bgName, OBJPROP_BORDER_TYPE, BORDER_FLAT);
      ObjectSetInteger(0, bgName, OBJPROP_SELECTABLE, false);
      ObjectSetInteger(0, bgName, OBJPROP_BACK, false);
   }

   color headFloatClr = (g_totalFloat > 0.0) ? clrLimeGreen
                      : (g_totalFloat < 0.0) ? clrTomato : clrGold;

   MakeLabel(g_panelPrefix + "head", x, y,
             StringFormat("PORTFOLIO DASHBOARD  Net: %+.2f  Open: %d  Float: %+.2f  [%s]",
                          g_totalNet, g_totalOpen, g_totalFloat,
                          TimeToString(TimeCurrent(), TIME_MINUTES)),
             clrGold, size + 1, true);

   MakeLabel(g_panelPrefix + "cols", x, y + dy,
             StringFormat("%-7s %-7s %10s %10s %6s %5s %10s %5s %10s  %s",
                          "magic", "tag", "net", "maxProfit", "trades", "win%", "maxDD", "open",
                          "float", "verdict"),
             clrDodgerBlue, size);

   int top = y + 2 * dy;

   for(int i = 0; i < shown; i++)
   {
      double winVal = (g_rows[i].wins + g_rows[i].losses > 0)
                      ? 100.0 * g_rows[i].wins / (g_rows[i].wins + g_rows[i].losses) : 0.0;
      string winPct = StringFormat("%3.0f%%", winVal);

      color clr = clrSilver;
      if(g_rows[i].openPos > 0)
         clr = (g_rows[i].floating >= 0.0) ? clrLime : clrOrangeRed;
      else if(g_rows[i].net > 0.0)
         clr = clrLimeGreen;
      else if(g_rows[i].net < 0.0)
         clr = clrTomato;

      if(g_rows[i].verdict == "DROP") clr = clrRed;

      MakeLabel(g_panelPrefix + "row" + IntegerToString(i), x, top + i * dy,
                StringFormat("%-7s %-7s %10.2f %10.2f %6d %5s %10.2f %5d %10.2f  %s",
                             IntegerToString(g_rows[i].magic), g_rows[i].tag,
                             g_rows[i].net, g_rows[i].maxProfit, g_rows[i].closed, winPct, g_rows[i].maxDd,
                             g_rows[i].openPos, g_rows[i].floating, g_rows[i].verdict),
                clr, size);
   }

   //--- clean up any stale row objects if shown count decreased
   for(int r = shown; r < 100; r++)
   {
      string oldRow = g_panelPrefix + "row" + IntegerToString(r);
      if(ObjectFind(0, oldRow) >= 0) ObjectDelete(0, oldRow);
      else break;
   }

   string footer = (g_count > shown)
                   ? StringFormat("... %d more engine(s) - full log in MQL5\\Files\\%s",
                                  g_count - shown, InpReportFile)
                   : "To toggle an engine: tick/untick InpRun_<magic> in AllEnginesEA";
   MakeLabel(g_panelPrefix + "foot", x, top + shown * dy + (dy / 2), footer, clrGray, size - 1);
   ChartRedraw(0);
}

void RemovePanel()
{
   for(int i = ObjectsTotal(0) - 1; i >= 0; i--)
   {
      string name = ObjectName(0, i);
      if(StringFind(name, g_panelPrefix) == 0) ObjectDelete(0, name);
   }
   ChartRedraw(0);
}

//+------------------------------------------------------------------+
//| lifecycle                                                         |
//+------------------------------------------------------------------+
int OnInit()
{
   g_base = (InpBaseBalance > 0.0) ? InpBaseBalance : AccountInfoDouble(ACCOUNT_BALANCE);
   LoadIdentity();
   EventSetTimer((int)MathMax(1, InpRefreshSec));
   Refresh();
   PrintFormat("PortfolioEA tracker running: %d engine(s), DD base %.2f.  Switch engines in " +
               "AllEnginesEA via InpRun_<magic>.", g_count, g_base);
   return INIT_SUCCEEDED;
}

void OnTimer()
{
   Refresh();
}

void OnTick()
{
   //--- the tracker works on a timer; ticks need no work here
}

void OnDeinit(const int reason)
{
   EventKillTimer();
   RemovePanel();
}
//+------------------------------------------------------------------+
