//+------------------------------------------------------------------+
//| PortfolioLauncher.mq5                                          |
//|                                  Copyright 2026, Master Strategy  |
//|                                                                   |
//| MT5 allows one EA per chart, so running the 65 generated EAs by   |
//| hand means 65 charts and 65 manual attaches.  This script does it |
//| for you: it reads EA_Launch\launch_plan.csv (generated by         |
//| validation/mt5_harness/gen_launcher.py), opens one chart per EA   |
//| and applies the matching template - which already carries the EA  |
//| and its inputs.                                                   |
//|                                                                   |
//| You attach ONE program, once.  Safe to re-run: EAs already        |
//| running are skipped.  Every result lands in                        |
//| MQL5\Files\EA_Launch\launch_status.csv.                            |
//|                                                                   |
//| NOTE ON PERMISSIONS (MT5 rule): an EA launched by ChartApplyTemplate
//| can only trade if the CALLING program has trade permission.  Run   |
//| this script with the "Algo Trading" button ON and "Allow Algo       |
//| Trading" ticked in its properties - START refuses otherwise.        |
//+------------------------------------------------------------------+
#property copyright "Master Strategy"
#property link      ""
#property version   "1.00"
#property script_show_inputs
#property description "Open + attach every EA listed in EA_Launch\\launch_plan.csv (one chart per EA)."
#property description "Modes: START (open+attach) / STOP (close these charts) / DRYRUN (report only)."
#property description "launch_plan.csv column 2 (enabled) switches an EA off without deleting it."

enum ENUM_LAUNCH_MODE
{
   LAUNCH_START  = 0,   // START  - open charts and attach the EAs
   LAUNCH_STOP   = 1,   // STOP   - close the charts running these EAs
   LAUNCH_DRYRUN = 2    // DRYRUN - report only, change nothing
};

input ENUM_LAUNCH_MODE InpMode      = LAUNCH_START;      // action
input int              InpGroup     = 0;                 // chart group (0 = every group)
input int              InpMaxCharts = 0;                 // safety cap (0 = no cap)
input bool             InpMinimise  = true;              // minimise opened charts (EAs keep running)
input bool             InpForce     = false;             // attach even if Algo Trading is OFF
input string           InpFolder    = "EA_Launch";       // folder inside MQL5\Files

struct SLaunchRow
{
   int      group;
   bool     enabled;             // launch_plan.csv column 2: 0 = switched off
   string   ea;
   string   symbol;
   int      tfMinutes;
   string   tfLabel;
   string   templateName;
   string   universe;
};

//+------------------------------------------------------------------+
//| minutes -> ENUM_TIMEFRAMES                                        |
//+------------------------------------------------------------------+
ENUM_TIMEFRAMES PeriodFromMinutes(const int minutes)
{
   switch(minutes)
   {
      case 1:    return PERIOD_M1;
      case 5:    return PERIOD_M5;
      case 15:   return PERIOD_M15;
      case 30:   return PERIOD_M30;
      case 60:   return PERIOD_H1;
      case 240:  return PERIOD_H4;
      case 1440: return PERIOD_D1;
   }
   return PERIOD_M5;
}

//+------------------------------------------------------------------+
//| read launch_plan.csv                                              |
//+------------------------------------------------------------------+
int ReadPlan(SLaunchRow &rows[])
{
   ArrayResize(rows, 0);
   string file = InpFolder + "\\launch_plan.csv";
   int h = FileOpen(file, FILE_READ | FILE_CSV | FILE_ANSI, ',');
   if(h == INVALID_HANDLE)
   {
      Print("PortfolioLauncher: cannot open MQL5\\Files\\", file,
            " (error ", GetLastError(), ").");
      Print("Copy the generated out/launch/ folder into MQL5\\Files\\", InpFolder, "\\ first.");
      return -1;
   }

   bool header = true;
   while(!FileIsEnding(h))
   {
      string grp  = FileReadString(h);
      if(StringLen(grp) == 0 && FileIsEnding(h)) break;
      string flag  = FileReadString(h);
      string ea    = FileReadString(h);
      string sym   = FileReadString(h);
      string tf    = FileReadString(h);
      string tpl   = FileReadString(h);
      string magic = FileReadString(h);
      string strat = FileReadString(h);
      string uni   = FileReadString(h);
      if(header)
      {
         header = false;
         if(grp == "group") continue;               // column header, not data
      }
      if(StringLen(ea) == 0) continue;

      int n = ArraySize(rows);
      ArrayResize(rows, n + 1);
      rows[n].group        = (int)StringToInteger(grp);
      rows[n].enabled      = (StringToInteger(flag) != 0);
      rows[n].ea           = ea;
      rows[n].symbol       = sym;
      rows[n].tfLabel      = tf;
      rows[n].tfMinutes    = (int)StringToInteger(tf);
      rows[n].templateName = (StringLen(tpl) > 0) ? tpl : ea;
      rows[n].universe     = uni;
   }
   FileClose(h);
   return ArraySize(rows);
}

//+------------------------------------------------------------------+
//| is `expert` the EA named in any plan row?                         |
//+------------------------------------------------------------------+
bool ExpertInPlan(const string expert, const SLaunchRow &rows[])
{
   if(StringLen(expert) == 0) return false;
   for(int i = 0; i < ArraySize(rows); i++)
      if(StringFind(expert, rows[i].ea) >= 0 || StringFind(rows[i].ea, expert) >= 0)
         return true;
   return false;
}

//+------------------------------------------------------------------+
//| chart (other than `exceptId`) already running this EA?            |
//+------------------------------------------------------------------+
long FindRunningChart(const string ea, const long exceptId)
{
   long id = ChartFirst();
   while(id >= 0)
   {
      long next = ChartNext(id);
      if(id != exceptId)
      {
         string exp = ChartGetString(id, CHART_EXPERT_NAME);
         if(StringLen(exp) > 0 && (StringFind(exp, ea) >= 0 || StringFind(ea, exp) >= 0))
            return id;
      }
      id = next;
   }
   return -1;
}

//+------------------------------------------------------------------+
//| Script entry point                                                |
//+------------------------------------------------------------------+
void OnStart()
{
   if(InpGroup < 0) { Print("InpGroup must be >= 0"); return; }

   //--- fill the timeframe minutes from the label if the plan carried "M5" style
   SLaunchRow rows[];
   int total = ReadPlan(rows);
   if(total <= 0) { if(total == 0) Print("PortfolioLauncher: launch_plan.csv is empty."); return; }
   for(int i = 0; i < total; i++)
   {
      if(rows[i].tfMinutes < 1)                     // fall back to the label form
      {
         string t = rows[i].tfLabel;
         if(t == "M1")      rows[i].tfMinutes = 1;
         else if(t == "M5") rows[i].tfMinutes = 5;
         else if(t == "M15")rows[i].tfMinutes = 15;
         else if(t == "M30")rows[i].tfMinutes = 30;
         else if(t == "H1") rows[i].tfMinutes = 60;
         else if(t == "H4") rows[i].tfMinutes = 240;
         else if(t == "D1") rows[i].tfMinutes = 1440;
         else               rows[i].tfMinutes = 5;
      }
   }

   PrintFormat("PortfolioLauncher: %d EA(s) in the plan, mode=%s, group=%s",
               total, EnumToString(InpMode), InpGroup == 0 ? "all" : IntegerToString(InpGroup));

   //--- STOP: close every chart running one of these EAs -----------------
   if(InpMode == LAUNCH_STOP)
   {
      int closed = 0;
      long id = ChartFirst();
      while(id >= 0)
      {
         long next = ChartNext(id);
         if(id != ChartID())
         {
            string exp = ChartGetString(id, CHART_EXPERT_NAME);
            if(ExpertInPlan(exp, rows))
            {
               PrintFormat("STOP: closing chart %I64d (%s %s, EA %s)",
                           id, ChartSymbol(id), EnumToString((ENUM_TIMEFRAMES)ChartPeriod(id)), exp);
               ChartClose(id);
               closed++;
            }
         }
         id = next;
      }
      PrintFormat("PortfolioLauncher: STOP done - %d chart(s) closed.", closed);
      return;
   }

   //--- START needs trade permission, otherwise the attached EAs are mute
   bool termOk = (bool)TerminalInfoInteger(TERMINAL_TRADE_ALLOWED);
   bool progOk = (bool)MQLInfoInteger(MQL_TRADE_ALLOWED);
   if(InpMode == LAUNCH_START && !(termOk && progOk) && !InpForce)
   {
      Print("---------------------------------------------------------------");
      Print("START refused: Algo Trading is OFF  (terminal=", termOk, ", program=", progOk, ")");
      Print("MT5 rule: an EA attached by ChartApplyTemplate can only trade if the");
      Print("CALLING program has trade permission.  Enable the 'Algo Trading'");
      Print("toolbar button and tick 'Allow Algo Trading' in the script properties,");
      Print("then run again - or set InpForce=true to attach anyway (the EAs will");
      Print("stay mute until you enable it).");
      Print("---------------------------------------------------------------");
      return;
   }

   //--- status log -------------------------------------------------------
   string statusFile = InpFolder + "\\launch_status.csv";
   FileDelete(statusFile);
   int sh = FileOpen(statusFile, FILE_WRITE | FILE_CSV | FILE_ANSI, ',');
   if(sh != INVALID_HANDLE)
      FileWrite(sh, "time", "mode", "ea", "symbol", "tf", "chart_id", "expert", "status");

   //--- START / DRYRUN ---------------------------------------------------
   int launched = 0, skipped = 0, failed = 0, noSymbol = 0, offPlan = 0;
   for(int i = 0; i < total; i++)
   {
      if(InpGroup > 0 && rows[i].group != InpGroup) continue;
      if(!rows[i].enabled)
      {
         offPlan++;
         PrintFormat("[%3d/%3d] %-45s %-7s %-6s -> DISABLED_IN_PLAN (enabled=0)",
                     i + 1, total, rows[i].ea, rows[i].symbol, rows[i].tfLabel);
         if(sh != INVALID_HANDLE)
            FileWrite(sh, TimeToString(TimeLocal(), TIME_DATE | TIME_SECONDS),
                      EnumToString(InpMode), rows[i].ea, rows[i].symbol, rows[i].tfLabel,
                      IntegerToString(0), "", "DISABLED_IN_PLAN");
         continue;
      }
      if(InpMaxCharts > 0 && launched >= InpMaxCharts)
      {
         PrintFormat("cap reached (%d) - remaining EAs left for the next run", InpMaxCharts);
         break;
      }

      string status = "";
      string expert = "";
      string sym    = rows[i].symbol;

      //--- symbol present at this broker?
      if(!SymbolSelect(sym, true) || !(bool)SymbolInfoInteger(sym, SYMBOL_SELECT))
      {
         status = "NO_SYMBOL_AT_BROKER";
         noSymbol++;
      }
      else
      {
         long running = FindRunningChart(rows[i].ea, ChartID());
         if(running >= 0)
         {
            status = "SKIP_ALREADY_RUNNING";
            expert = ChartGetString(running, CHART_EXPERT_NAME);
            skipped++;
         }
         else
         {
            long cid = 0;
            if(InpMode == LAUNCH_DRYRUN)
            {
               status = "DRYRUN_WOULD_OPEN";
            }
            else
            {
               cid = ChartOpen(sym, PeriodFromMinutes(rows[i].tfMinutes));
               if(cid == 0)
               {
                  status = "OPEN_FAILED";
                  failed++;
               }
               else
               {
                  string path = "\\Files\\" + InpFolder + "\\templates\\" + rows[i].templateName + ".tpl";
                  if(!ChartApplyTemplate(cid, path))
                  {
                     status = "APPLY_REJECTED";
                     failed++;
                  }
                  else
                  {
                     for(int t = 0; t < 6; t++)          // apply is queued; wait for the EA
                     {
                        Sleep(400);
                        expert = ChartGetString(cid, CHART_EXPERT_NAME);
                        if(StringLen(expert) > 0) break;
                     }
                     if(StringLen(expert) == 0)
                     {
                        status = "NO_EXPERT_AFTER_APPLY";
                        failed++;
                     }
                     else if(StringFind(expert, rows[i].ea) < 0)
                     {
                        status = "ATTACHED_OTHER:" + expert;   // template name path mismatch
                        failed++;
                     }
                     else
                     {
                        status = "OK";
                        launched++;
                     }
                     if(InpMinimise) ChartSetInteger(cid, CHART_IS_MINIMIZED, true);
                  }
               }
            }
         }
      }

      PrintFormat("[%3d/%3d] %-45s %-7s %-6s -> %s%s",
                  i + 1, total, rows[i].ea, rows[i].symbol, rows[i].tfLabel,
                  status, StringLen(expert) > 0 ? " (" + expert + ")" : "");
      if(sh != INVALID_HANDLE)
         FileWrite(sh, TimeToString(TimeLocal(), TIME_DATE | TIME_SECONDS),
                   EnumToString(InpMode), rows[i].ea, rows[i].symbol, rows[i].tfLabel,
                   IntegerToString(0), expert, status);
   }

   if(sh != INVALID_HANDLE) FileClose(sh);
   PrintFormat("PortfolioLauncher done: launched %d | already running %d | disabled in plan %d | missing symbol %d | failed %d",
               launched, skipped, offPlan, noSymbol, failed);
   if(failed > 0)
      Print("Failed rows are listed above and in MQL5\\Files\\", statusFile,
            ".  A NO_EXPERT_AFTER_APPLY usually means the template's name= line does not");
   Print("match the compiled EA's Navigator path - compare templates\\<EA>.tpl with a");
   Print("template you saved by hand, or re-run gen_launcher.py --base-tpl <that file>.");
}
//+------------------------------------------------------------------+
