#!/usr/bin/env python3
"""Render each Glimpse summary markdown into a print-styled HTML, then
print-to-PDF with headless Edge."""
import html
import re
import subprocess
from pathlib import Path

EDGE = r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
SRC = Path("glimpse")
DST = Path("glimpse-pdf")

CSS = """
@page { size: A4; margin: 16mm 14mm; }
* { box-sizing: border-box; }
body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
       color: #16181d; max-width: 760px; margin: 0 auto; padding: 8px 4px;
       font-size: 12.5px; line-height: 1.55; }
h1 { font-size: 26px; line-height: 1.2; margin: 0 0 6px; color: #0b0c0f; }
.meta { color: #5b616e; font-size: 11.5px; margin: 0 0 18px;
        padding-bottom: 12px; border-bottom: 2px solid #e6e8ec; }
.meta a { color: #2f6feb; text-decoration: none; }
h2 { font-size: 17px; margin: 22px 0 8px; color: #0b0c0f;
     padding-left: 10px; border-left: 4px solid #2f6feb; }
h3 { font-size: 14.5px; margin: 16px 0 6px; color: #1c2027; }
h4 { font-size: 13px; margin: 14px 0 5px; color: #1c2027; }
p  { margin: 0 0 10px; }
li { margin: 0 0 6px; }
ul { margin: 0 0 12px; padding-left: 20px; }
blockquote { margin: 12px 0; padding: 8px 12px; background: #f5f7fa;
             border-left: 4px solid #c3c9d4; color: #2b3038; }
strong { color: #0b0c0f; }
footer { margin-top: 26px; padding-top: 10px; border-top: 1px solid #e6e8ec;
         color: #8a919e; font-size: 10.5px; }
"""

INLINE = [
    (re.compile(r"\*\*(.+?)\*\*"), r"<strong>\1</strong>"),
    (re.compile(r"`([^`]+)`"), r"<code>\1</code>"),
    (re.compile(r"\[([^\]]+)\]\(([^)]+)\)"), r'<a href="\2">\1</a>'),
]


def md_to_html(text: str) -> str:
    out, buf = [], []

    def flush():
        if buf:
            out.append("<p>" + " ".join(buf) + "</p>")
            buf.clear()

    for raw in text.split("\n"):
        line = raw.rstrip()
        if not line.strip():
            flush()
            continue
        if line.startswith("# "):
            flush()
            out.append(f"<h1>{html.escape(line[2:])}</h1>")
        elif line.startswith("## "):
            flush()
            out.append(f"<h2>{html.escape(line[3:])}</h2>")
        elif line.startswith("### "):
            flush()
            out.append(f"<h3>{html.escape(line[4:])}</h3>")
        elif re.match(r"^[-*]\s+", line):
            flush()
            if not out or not out[-1].startswith("<ul"):
                out.append("<ul>")
            item = re.sub(r"^[-*]\s+", "", line)
            out.append(f"<li>{inline(item)}</li>")
            out.append("__CLOSEUL__")
        else:
            buf.append(inline(line))

    flush()
    # collapse the bookkeeping closes
    html_out, open_list = [], False
    for chunk in out:
        if chunk == "__CLOSEUL__":
            if open_list:
                html_out.append("</ul>")
                open_list = False
            continue
        if chunk.startswith("<ul") and open_list:
            html_out.append("</ul>")
        if chunk.startswith("<ul"):
            open_list = True
        elif chunk.startswith("<") and not chunk.startswith("<li") and open_list:
            html_out.append("</ul>")
            open_list = False
        html_out.append(chunk)
    if open_list:
        html_out.append("</ul>")
    return "\n".join(html_out)


def inline(s: str) -> str:
    s = html.escape(s, quote=False)
    for rx, rep in INLINE:
        s = rx.sub(rep, s)
    return s


def build(md_path: Path) -> Path:
    text = md_path.read_text(encoding="utf-8")
    lines = text.split("\n")
    title = lines[0].lstrip("# ").strip()
    yt = next((l for l in lines if l.startswith("- YouTube:")), "")
    gp = next((l for l in lines if l.startswith("- Glimpse:")), "")
    body = "\n".join(
        l for l in lines if not l.startswith("- YouTube:") and not l.startswith("- Glimpse:")
    )
    meta = []
    if yt:
        url = yt.split(":", 1)[1].strip()
        meta.append(f'<a href="{url}">Watch on YouTube</a>')
    if gp:
        url = gp.split(":", 1)[1].strip()
        meta.append(f'<a href="{url}">Glimpse summary</a>')

    doc = (
        "<!doctype html><html><head><meta charset='utf-8'>"
        f"<title>{html.escape(title)}</title><style>{CSS}</style></head><body>"
        f"<h1>{html.escape(title)}</h1>"
        f"<p class='meta'>{' &middot; '.join(meta)}</p>"
        f"{md_to_html(body)}"
        "<footer>Summary generated by Glimpse (glimpse.wozart.com) from the "
        "original YouTube video. Source: chartfanatics.com/strategies</footer>"
        "</body></html>"
    )
    html_path = DST / (md_path.stem + ".html")
    html_path.write_text(doc, encoding="utf-8")
    return html_path


def to_pdf(html_path: Path) -> Path:
    pdf_path = html_path.with_suffix(".pdf")
    cmd = [
        EDGE, "--headless", "--disable-gpu", "--no-sandbox",
        "--no-pdf-header-footer",
        f"--print-to-pdf={pdf_path.resolve()}", html_path.resolve().as_uri(),
    ]
    subprocess.run(cmd, capture_output=True, timeout=120)
    return pdf_path


def main():
    DST.mkdir(exist_ok=True)
    ok = bad = 0
    for md in sorted(SRC.glob("*.md")):
        try:
            h = build(md)
            p = to_pdf(h)
            if p.exists() and p.stat().st_size > 1000:
                print(f"OK   {p.name}  {p.stat().st_size} bytes")
                ok += 1
            else:
                print(f"FAIL {md.name}: no pdf")
                bad += 1
        except Exception as e:
            print(f"FAIL {md.name}: {e}")
            bad += 1
    print(f"=== pdf ok={ok} fail={bad} ===")


if __name__ == "__main__":
    main()
